# Generated by Django 3.2 on 2021-08-10 14:49

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=60)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('above_war_unit', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_unit', to='war_unit.warunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
