# Generated by Django 2.2.6 on 2019-11-10 21:26

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import rtbn.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_item_name', models.CharField(max_length=60)),
                ('address_item_type', enumfields.fields.EnumField(enum=rtbn.models.TypePlace, max_length=1)),
                ('above_address_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbn.AddressItem')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg_locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbn.AddressItem')),
            ],
        ),
        migrations.CreateModel(
            name='CallingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallingTeamDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.CallingTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Captivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_captivity', models.DateField(null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Camp')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mobilization', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Неизвестно', max_length=30)),
                ('name_distortion', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(default='Неизвестно', max_length=30)),
                ('surname_distortion', models.CharField(max_length=30, null=True)),
                ('father_name', models.CharField(max_length=30, null=True)),
                ('father_name_distortion', models.CharField(max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
                ('born_locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='born', to='rtbn.AddressItem')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Call')),
                ('calling_teams', models.ManyToManyField(through='rtbn.CallingTeamDirection', to='rtbn.CallingTeam')),
                ('live_locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='rtbn.AddressItem')),
            ],
        ),
        migrations.CreateModel(
            name='WarArchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WarServe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtbn.Person')),
                ('date_of_burial', models.DateField(null=True)),
                ('cemetery', models.CharField(max_length=60)),
                ('number_plot', models.CharField(max_length=30)),
                ('number_line', models.CharField(max_length=30)),
                ('number_thumb', models.CharField(max_length=30)),
                ('address_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_item_act_id', to='rtbn.AddressItem')),
                ('address_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_item_doc_id', to='rtbn.AddressItem')),
            ],
        ),
        migrations.CreateModel(
            name='WarUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('warunit_type', enumfields.fields.EnumField(enum=rtbn.models.WarUnitType, max_length=1)),
                ('above_war_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbn.WarUnit')),
                ('military_personnel', models.ManyToManyField(through='rtbn.WarServe', to='rtbn.Person')),
            ],
        ),
        migrations.AddField(
            model_name='warserve',
            name='war_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.WarUnit'),
        ),
        migrations.CreateModel(
            name='WarOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('participants', models.ManyToManyField(through='rtbn.WarArchievement', to='rtbn.WarServe')),
            ],
        ),
        migrations.AddField(
            model_name='wararchievement',
            name='war_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.WarOperation'),
        ),
        migrations.AddField(
            model_name='wararchievement',
            name='war_serve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.WarServe'),
        ),
        migrations.CreateModel(
            name='MilitaryEnlistmentOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.AddressItem')),
            ],
        ),
        migrations.CreateModel(
            name='InfirmaryCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField(null=True)),
                ('period_to', models.DateField(null=True)),
                ('name', models.CharField(max_length=60)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Camp')),
                ('captivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Captivity')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('direction_name', models.CharField(max_length=256)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Hospital')),
                ('hospital_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbn.AddressItem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Person')),
                ('war_unit_consist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.WarUnit')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='patients',
            field=models.ManyToManyField(through='rtbn.Hospitalization', to='rtbn.Person'),
        ),
        migrations.AddField(
            model_name='captivity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Person'),
        ),
        migrations.AddField(
            model_name='captivity',
            name='place_of_captivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbn.AddressItem'),
        ),
        migrations.CreateModel(
            name='CampArbeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField(null=True)),
                ('period_to', models.DateField(null=True)),
                ('name', models.CharField(max_length=60)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Camp')),
                ('captivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Captivity')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='prisoners',
            field=models.ManyToManyField(through='rtbn.Captivity', to='rtbn.Person'),
        ),
        migrations.AddField(
            model_name='callingteamdirection',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Person'),
        ),
        migrations.AddField(
            model_name='call',
            name='military_enlistment_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.MilitaryEnlistmentOffice'),
        ),
        migrations.AddField(
            model_name='call',
            name='mobilization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Mobilization'),
        ),
        migrations.AddField(
            model_name='call',
            name='warunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtbn.WarUnit'),
        ),
        migrations.CreateModel(
            name='AddingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_defector', models.BooleanField()),
                ('is_gestapo', models.BooleanField()),
                ('is_frei', models.BooleanField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rtbn.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Reburial',
            fields=[
                ('burial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtbn.Burial')),
                ('date_of_reburial', models.DateField(null=True)),
                ('reburial_cause', models.CharField(max_length=60, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtbn.AddressItem')),
            ],
        ),
    ]
